name: Flutter CI/CD Exercise

on: [push]

jobs:
    setup-and-test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version:
              '3.13.9'
            cache: true

        - name: Install ChromeDriver
          run: |
            wget -N https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.71/linux64/chromedriver-linux64.zip -P ~/
            unzip ~/chromedriver-linux64.zip -d ~/
            rm ~/chromedriver-linux64.zip
            sudo mv -f ~/chromedriver-linux64 /usr/local/bin/chromedriver
            sudo chown root:root /usr/local/bin/chromedriver
            sudo chmod 0755 /usr/local/bin/chromedriver
        
        - name: Flutter Unit/Widget Testing
          run: flutter test

        - name: Flutter Integration Testing
          run: |
            chromedriver --port=4444 --trace-buffer-size=100000 &
            flutter drive \
                --verbose-system-logs \
                -d web-server \
                --driver=test_driver/integration_test.dart \
                --target=integration_test/widget_test.dart